---
- name: Deploy local Docker image container to VM
  hosts: webservers 
  become: true
  vars:
    local_image_tar: "{{ tar_image }}"    # adjust this path on your control machine
    image_name: "{{ image_tag }}"          # the image tag inside the tarball
    container_name: advent2024-web
  tasks:
    - name: Copy local Docker image tarball to VM
      ansible.builtin.copy:
        src: "{{ local_image_tar }}"
        dest: "/tmp/{{ local_image_tar | basename }}"
        mode: '0644'

    - name: Wait for Docker daemon to be ready
      ansible.builtin.command: docker info
      register: docker_ready
      retries: 6
      delay: 10 
      until: docker_ready.rc == 0
      become: true

    - name: Load Docker image from tarball
      ansible.builtin.command: >
        docker load -i /tmp/{{ local_image_tar | basename }}

    - name: Run Docker container from local image
      community.docker.docker_container:
        name: "{{ inventory_hostname }}"
        image: "{{ image_name }}"
        state: started
        restart_policy: unless-stopped
        ports:
          - "8080:8080"