variable "region" {
    description = "azure region"
    default = "westeurope"
}

variable "env" {
    description = "environment name"
    default = "dev"
}
variable "docker_image" {
    description = "image for the ACI container"
    default = "jsafar/advent2024.web:dev"
}

// suffix for the ACI name
resource "random_string" "dns_name_suffix" {
    length = 6
    upper = false
    special = false
}

variable "app_dns_name" {
    description = "app FQDN, for certification generation and CNAME registration"
}
variable "dns_provider" {
    description = "DNS provider for the Let's Encrypt certification generation"
}

variable "email" {
    description = "Email for the Let's Encrypt registration"
}

variable "dns_zone" {
    description = "dnz zone for CNAME registration"
}

variable "aci_app_env_map" {
    description = "ENV variables for the ACI container"
    type = map(string)
    default = {}
}

variable "aci_app_env_map_secret" {
    description = "ENV secrets for the ACI container - will be stored as secrets"
    type = map(string)
    default = {}
    sensitive = true
}
// calculated values based on the ENV variables provided to the container
locals {
    app_port = contains(keys(var.aci_app_env_map), "PORT") ? var.aci_app_env_map["PORT"] : 8080
    cert = contains(keys(var.aci_app_env_map), "TLS_CERT_FILE") ? file(var.aci_app_env_map["TLS_CERT_FILE"]) : ""
    key = contains(keys(var.aci_app_env_map), "TLS_KEY_FILE") ? file(var.aci_app_env_map["TLS_KEY_FILE"]) : ""
    enable_https = contains(keys(var.aci_app_env_map), "ENABLE_HTTPS") ? var.aci_app_env_map["ENABLE_HTTPS"] : "false"
    use_acme = local.enable_https == "true" && ( local.cert == "" || local.key == "" )
}

// key map for the secrets - nonsensitive so it can be referenced in the code
locals {
    aci_app_env_map_secret_keys = nonsensitive(keys(var.aci_app_env_map_secret))
}

variable "tenant_id" {
    description = "Tenant Id of the Key Vault"
    default = {}
}

// load information generated by bootstrap
locals {
    acr = jsondecode(file("../../acr.json"))
    config_store = jsondecode(file("../../config_store.json"))
}

// OIDC - gh action application name - for ACI refresh
variable "gh_actions_application_name" {
    description = "OIDC - application name for GitHub actions - needs to be same as in bootstrap"
    default = "gh-actions"
}