name: CI / Docker Build

on:
  pull_request:
    branches:
      - master
      - 'feature/**'
  push:
    branches:
      - master
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up branch name variable
        id: vars
        run: |
          # Strip refs/heads/ prefix and replace slashes with dashes
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}" | tr '/' '-')
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Run unit tests
        run: |
          for mod in ./pkg/*/; do
            if [ -f "$mod/go.mod" ]; then
              echo "Testing $mod"
              go test "$mod/..."
            fi
          done

      - name: Build Docker images
        run: |
          TIMESTAMP=$(date +%s)
          docker build -f build/ci/docker/cli.Dockerfile -t advent2024.cli:${BRANCH_NAME}-${TIMESTAMP} .
          docker build -f build/ci/docker/web.Dockerfile -t advent2024.web:${BRANCH_NAME}-${TIMESTAMP} .

      # - name: Log in to Docker Hub
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Push Docker images
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      #   run: |
      #     TIMESTAMP=$(date +%s)
      #     docker tag advent2024.cli:${BRANCH_NAME}-${TIMESTAMP} yourdockerhub/advent2024.cli:latest
      #     docker tag advent2024.web:${BRANCH_NAME}-${TIMESTAMP} yourdockerhub/advent2024.web:latest

      #     docker push yourdockerhub/advent2024.cli:latest
      #     docker push yourdockerhub/advent2024.web:latest