name: CMD cli - Pull Request

on:
  pull_request:
    paths:
      - '.github/workflows/cmd-cli-pr.yml'
      - 'build/ci/docker/cli.Dockerfile'
      - 'cmd/cli/**'
      - 'pkg/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Unit Tests
        run: |
          for mod in ./pkg/*/; do
            if [ -f "$mod/go.mod" ]; then
              echo "Testing $mod"
              go test "$mod/..."
            fi
          done

      - name: Run CLI Tests
        run: |
          echo "Running cli tests..."
          go test ./cmd/cli/...

          