name: CMD cli - Push to release branches

on:
  push:
    branches:
      - dev
      - stage
      - master
    paths:
      - '.github/workflows/cmd-cli-release.yml'
      - 'build/ci/docker/cli.Dockerfile'
      - 'cmd/cli/**'
      - '/pkg/**'

permissions:
  contents: write

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: bump
        uses: ./.github/actions/bump-version
        with:
          branch-name: ${{github.ref_name}}
          work-dir: cmd/cli
          tag-prefix: cmd/cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: bump_version
    if: needs.bump_version.outputs.bumped == 'true'

    permissions:
      actions: write
      contents: read

    env:
      NEXT_VER: ${{ needs.bump_version.outputs.next-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up branch name variable
        id: vars
        run: |
          # Strip refs/heads/ prefix and replace slashes with dashes
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}" | tr '/' '-')
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

          TIMESTAMP=$(date +%s)
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV

      - name: Build Docker images
        run: |
          docker build -f build/ci/docker/cli.Dockerfile -t jsafar/advent2024.cli:${NEXT_VER} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker images
        run: |
          docker tag jsafar/advent2024.cli:${NEXT_VER} jsafar/advent2024.cli:${BRANCH_NAME}
          
          docker push jsafar/advent2024.cli:${BRANCH_NAME}
          docker push jsafar/advent2024.cli:${NEXT_VER}

      - name: Push Docker images - master
        if: github.ref == 'refs/heads/master'
        run: |
          docker tag jsafar/advent2024.cli:${NEXT_VER} jsafar/advent2024.cli:latest

          docker push jsafar/advent2024.cli:latest