name: CMD web - Push to release branches

on:
  push:
    branches:
      - dev
      - stage
      - master
    paths:
      - '.github/workflows/cmd-web-release.yml'
      - 'build/ci/docker/web.Dockerfile'
      - 'cmd/web/**'
      - '/pkg/**'

permissions:
  contents: write

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: bump
        uses: ./.github/actions/bump-version
        with:
          branch-name: ${{github.ref_name}}
          work-dir: cmd/web
          tag-prefix: cmd/web
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: bump_version
    if: needs.bump_version.outputs.bumped == 'true'

    permissions:
      actions: write
      contents: read

    env:
      NEXT_VER: ${{ needs.bump_version.outputs.next-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker images
        run: |
          docker build -f build/ci/docker/web.Dockerfile -t jsafar/advent2024.web:${NEXT_VER} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker images
        run: |
          docker push jsafar/advent2024.web:${NEXT_VER}

      - name: Push Docker images - master
        if: github.ref == 'refs/heads/master'
        run: |
          docker tag jsafar/advent2024.web:${NEXT_VER} jsafar/advent2024.web:latest

          docker push jsafar/advent2024.web:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      actions: write
      contents: read

    steps:      
      - name: Trigger ECS deploy workflow_run
        run: gh workflow run .github/workflows/ecs-image-change.yml --ref ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}