name: Environments - Local - Push to release branches

on:
  push:
    branches:
      - dev
      - stage
      - master
    paths:
      - 'environments/local/**'
      - '.github/workflows/environments-local-release.yml'

permissions:
  contents: write

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/bump-version
        with:
          branch-name: ${{github.ref_name}}
          work-dir: ./environmets/local
          tag-prefix: environments/local
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          