name: Environments - Local - Pull Request

on:
  pull_request:
    paths:
      - 'environments/local/**'
      - '.github/workflows/environments-local.pr.yml'

permissions:
  content: write

defaults:
  run:
    working-directory: ./environments/local

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install SemVer
        run: |
          npm install -g semver

      - name: version
        id: bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Setup git

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/${{ github.repository }}.git

          # Read current version

          CURR_VER=$(cat VERSION 2>/dev/null || echo "0.0.0")
          echo "Current version: $CURR_VER"

          # Determine next version
          
          if [[ "${GITHUB_REF}" == "refs/heads/dev" ]]; then
            NEXT_VER=$(semver "$CURR_VER" -i prerelease --preid dev)
          elif [[ "${GITHUB_REF}" == "refs/heads/stage" ]]; then
            NEXT_VER=$(semver "$CURR_VER" -i prerelease --preid stage)
          else
            NEXT_VER=$(semver "$CURR_VER" -i patch)
          fi
          echo "Next version: $NEXT_VER"

          # Update VERSION file
          
          echo "$NEXT_VER" > VERSION

          # Commit and tag
          git add VERSION
          git commit -m "chore: bump version to $NEXT_VER"
          git tag "v$NEXT_VER"

          # Push commit and tag
          git push origin HEAD --tags