name: Environments - AWS Stage - Push to release branches

on:
  push:
    branches:
      - dev
      - stage
      - master
    paths:
      - 'environments/aws/stage/**'
      - '.github/workflows/environments-aws-stage-release.yml'

permissions:
  contents: write

jobs:
  bump_version:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{github.ref_name}}-bump-lock
      cancel-in-progress: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Bump Version of Component
        id: bump
        uses: ./.github/actions/bump-version
        with:
          branch-name: ${{github.ref_name}}
          work-dir: environments/aws/stage
          tag-prefix: environments/aws/stage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}