name: Master - Push to release branches

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump Version
        uses: ./.github/actions/bump-version
        with:
          branch-name: ${{github.ref_name}}
          tag-prefix: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
