name: Modules - AWS - Infra - Push to release branches

on:
  push:
    branches:
      - dev
      - stage
      - master
    paths:
      - 'modules/aws/infra/**'
      - '.github/workflows/modules-aws-infra-release.yml'

permissions:
  contents: write

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/bump-version
        with:
          branch-name: ${{github.ref_name}}
          work-dir: modules/aws/infra
          tag-prefix: modules/aws/infra
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
