name: Test pull request

on:
  pull_request:
    branches:
    - master
    - 'feature/**'  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Run unit tests
        run: |
          for mod in ./pkg/*/; do
            if [ -f "$mod/go.mod" ]; then
              echo "Testing $mod"
              go test "$mod/..."
            fi
          done
          
      - name: Build the Docker image
        run: docker build --file build/ci/docker/cli.Dockerfile --tag advent2024:$(date +%s) .